### ISSUE TITLE
Callback: Error object is `null` although request was not successful

### ISSUE THREAD

**Issue by svenmueller** [sphereio/sphere-node-connect#1]
I would expect that the callback is called with error not `null` when the REST request wasn' sucessful

Example:

```
@sync = new OrderSync config: Config.staging

@sync._rest.DELETE "/product-types/07d76cec-4c92-4c51-bf85-074ab329dcbc" (error, response, body) =>
  console.log "error #{error}"
  console.log "response #{response}"
  console.log "body #{body}"

```

``` bash
# console log
error null
response [object Object]
body {"statusCode":400,"message":"Missing version number","errors":[{"code":"InvalidOperation","message":"Missing version number"}]}
```

**Comment by emmenko** [comment]
The HTTP API returns always a JSON, either with what you requested or some error messages.

http://commercetools.de/dev/http-api.html

If there is an `error` it comes from the `request` http client.

https://github.com/mikeal/request
http://nodejs.org/api/http.html#http_class_http_clientrequest

**Comment by emmenko** [comment]
I will mention this in the README

**Comment by svenmueller** [comment]
ok then the behavior makes kind of sense, thx!
