### ISSUE TITLE
Move Logger to a separate repo

### ISSUE THREAD

**Issue by emmenko** [sphereio/sphere-node-connect#6]
In order to make the Logger class extendable without requiring the `sphere-node-connect` package we should move this in a separate repository (or integrate it in `sphere-node-utils`)

**Comment by hajoeichler** [comment]
Very good idea, as I have a dependency to `sphere-node-connect` only because of the logger.
We could also reexport the Logger in `sphere-node-client`, but not sure if this is good style?
