### ISSUE TITLE
Provide functionality to renew the expired access token

### ISSUE THREAD

**Issue by OlegIlyenko** [sphereio/sphere-node-connect#7]
If application is running for more than 3 days (which is the default expiration time for the OAuth2 access token), then access token would expire. At this point it would be nice if `sphere-node-connect` would be able to automatically (and transparently) renew it.

Because of the asynchronous nature of this operation, all incoming requests should be buffered and resumed as soon as new access token is arrived and ready to be used for the other HTTP requests.

**Comment by hajoeichler** [comment]
Can't we actively re-new the token after 70h to avoid the buffering?

**Comment by OlegIlyenko** [comment]
@hajoeichler yeah, it's another approach. We know the expiration date, so we can have a background task that renews it in the background shortly before it expires. I like this approach.

**Comment by emmenko** [comment]
I would keep it simpler:
- incoming request
- is `access_token` valid?
- _no_ -> get new `access_token`
- _yes_ -> continue

**Comment by emmenko** [comment]
If multiple requests are coming while the `access_token` is being renewed, they all request a new one (I think), but it should be tolerable.

**Comment by OlegIlyenko** [comment]
the problem is that `getAccessTocken` is asynchronous operation. If you implement it like this, then under heavy load you can request 1000s of tokens at the same time from which only 1 would be used

**Comment by emmenko** [comment]
That's what I said yes :)

**Comment by emmenko** [comment]
But again, in that case I would prefer that the client checks if the token is expired or not before triggering all those requests

**Comment by emmenko** [comment]
I would not like to implement complex logic here

**Comment by gogregor** [comment]
I agree with Oleg that we should avoid requesting 1000s of tokens.

**Comment by OlegIlyenko** [comment]
@emmenko You would like to keep node-connect simple in order to implement low-level API and then implement more complex logic in the node-client. Do I understand this correctly? If so, then I think we should not implement this logic in the `node-connect` at all. IMHO, it would not be correct to implement the "simple" variant of this feature and not to take this issue into the consideration. 

I also think we need to look at the initial token retrieval logic, which has the same issue, as far as I can tell. It's already implemented in the `node-connect`, and in my opinion it shares the same abstraction layer with token renewal feature.

**Comment by emmenko** [comment]
Sure, let's talk about this during the node.js "hackaton day" ;)

**Comment by OlegIlyenko** [comment]
jup :)

**Comment by emmenko** [comment]
Issue moved to new repo
