### ISSUE TITLE
Consider using "debug" for logging

### ISSUE THREAD

**Issue by emmenko** [sphereio/sphere-node-connect#9]
https://github.com/visionmedia/debug

Advantages:
- ability to get only desired output via namespacing (e.g.: `DEBUG=rest`)
- easy to use
- normal output to stdout, which can be just piped to log files when used in production (e.g.: `2>/var/log/stderr.log`)

Disadvantages: 
- no more JSON logs

**Comment by svenmueller** [comment]
the advantange of json logs is that logentries can automatically detects fields which can then be used in search queries

**Comment by emmenko** [comment]
Done here https://github.com/sphereio/sphere-node-client/issues/42
